server:
  port: 9000
Spring:
  profiles:
    active: '@profiles.active@'
  datasource:
    url: jdbc:mysql://localhost:3306/poi?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      pool-name: poiPool
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update        